### ISSUE TITLE
Possible Listing 12-36 / 12-38 Issue

### ISSUE THREAD

**Issue by doug-holtsinger** [CodeMouse92/DeadSimplePython#4]
If I call bitwise_and() with these values, I get a Python exception:

bits = b'\xf1\x22\x33\x44'
bitfilter = b'\xff\xff\xff\xff'
result = bitwise_and(bits, bitfilter, byteorder='big')

Traceback (most recent call last):
  File "/cygdrive/c/TechResources/Python/Practice/./c.py", line 21, in <module>
    result = bitwise_and(bits, bitfilter, byteorder='big')
  File "/cygdrive/c/TechResources/Python/Practice/./c.py", line 11, in bitwise_and
    return result.to_bytes(size, byteorder, signed=True)
OverflowError: int too big to convert

If I drop the signed=True argument in listing 12-38, then I get the expected result of 0xf1223344

def bitwise_and(left, right, *, byteorder):
    size = max(len(left), len(right))
    left = int.from_bytes(left, byteorder=byteorder)
    right = int.from_bytes(right, byteorder=byteorder)
    result = left & right
    return result.to_bytes(size, byteorder, signed=True)

I am greatly enjoying the book.  It's one of the few reference books sitting on my shelf.

**Comment by CodeMouse92** [comment]
Hey, good catch! In fact, `int.from_bytes` has a default argument of `signed=False` that I utterly overlooked. So, `result.to_bytes(..., signed=True)` actually mismatches, resulting in the overflow.

```python
bits = b'\xf1\x22\x33\x44'
bitfilter = b'\xff\xff\xff\xff'
left = int.from_bytes(bits, byteorder='big', signed=False)  # 4045550404
right = int.from_bytes(bitfilter, byteorder='big', signed=False)  # 4294967295
result = left & right  # 4045550404
result.to_bytes(4, byteorder='big', signed=True)  # OverflowError: int too big to convert
result.to_bytes(5, byteorder='big', signed=True)  # b'\x00\xf1"3D'  (which is 0x00f1223344)
```

Interestingly, the size mismatch will not occur if we interpret the incoming values as two's complement as well...

```python
bits = b'\xf1\x22\x33\x44'
bitfilter = b'\xff\xff\xff\xff'
left = int.from_bytes(bits, byteorder='big', signed=True)  # -249416892
right = int.from_bytes(bitfilter, byteorder='big', signed=True)  # -1
result = left & right  # -249416892
result.to_bytes(4, byteorder='big', signed=True)  # b'\x00\xf1"3D'  (which is 0xf1223344)
```

However, if I apply that to my own original example, I don't get the correct results:

```python
bits = b'\xcc\xcc\xcc'
bitfilter = b'\xaa\xaa'
left = int.from_bytes(bits, byteorder='big', signed=True)  # -3355444
right = int.from_bytes(bitfilter, byteorder='big', signed=True)  # -21846
result = left & right  # -3372920
result.to_bytes(3, byteorder='big', signed=True)  # b'\xcc\x88\x88' (this is wrong!)
```

That's because instead of `0xAAAA` getting padded to `0x00AAAAA`, it's padded to `0xFFAAAA`...and `0xFFAAAA & 0xCCCCCC` is `0xCC8888`.

```python
bits = b'\xcc\xcc\xcc'
bitfilter = b'\x00\xaa\xaa'
left = int.from_bytes(bits, byteorder='big', signed=True)  # -3355444
right = int.from_bytes(bitfilter, byteorder='big', signed=True)  # 43690
result = left & right  # 34952
result.to_bytes(3, byteorder='big', signed=True)  # b'\x00\x88\x88' (this is wrong!)
```

My original error in thinking was that I could theoretically get two integers `left` and `right` such that `left & right` yielded a negative number. However, one can only get a negative value in a bitwise if both operands are negative, and negative numbers can only be produced if `signed=True`.

Whew. Sneaky little issue that got past several senior software engineers. Well done!

I just got word from my publisher that they're doing a reprint of the book, so I'll ensure this makes it into the new printing.

```python
def bitwise_and(left, right, *, byteorder):
    size = max(len(left), len(right))
    left = int.from_bytes(left, byteorder=byteorder, signed=False)
    right = int.from_bytes(right,  byteorder=byteorder, signed=False)
    result = left & right
    return result.to_bytes(size, byteorder=byteorder, signed=False)

bits = b'\xcc\xcc\xcc'
bitfilter = b'\xaa\xaa'
result = bitwise_and(bits, bitfilter, byteorder='big')
print(result)  # prints "b'\x00\x88\x88'"

bits = b'\xf1\x22\x33\x44'
bitfilter = b'\xff\xff\xff\xff'
result = bitwise_and(bits, bitfilter, byteorder='big')
print(result)  # prints "b'\xF1\x22\x33\x44'"
```
